channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.2
  - psutil==5.9.5
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
