name: CI/CD - Build and Push Docker with MLflow Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: nurfdlh/students-performance-model

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow scikit-learn pandas numpy flask

      - name: Run Model Training
        run: |
          python modeling.py

      - name: Get latest run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          if [ -z "$RUN_ID" ]; then
            echo "Run ID tidak ditemukan. Pastikan model disimpan di MLflow."
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID: $RUN_ID"

      - name: Download Model Artifact from MLflow
        run: |
          mkdir -p model_artifact
          mlflow artifacts download --artifact-uri "runs:/$RUN_ID/model" --dst model_artifact

      - name: Write Dockerfile
        run: |
          echo "FROM python:3.11-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY model_artifact /app/model" >> Dockerfile
          echo "COPY serve.py /app/serve.py" >> Dockerfile
          echo "RUN pip install mlflow scikit-learn pandas numpy flask" >> Dockerfile
          echo 'CMD ["python", "serve.py"]' >> Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE:latest .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE:latest
