name: Deploy Student Performance Model

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-deploy:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/smithdilah/students_dagshub.mlflow
      MLFLOW_TRACKING_USERNAME: smithdilah
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check environment
        run: |
          python --version
          echo "URI  : $MLFLOW_TRACKING_URI"
          echo "USER : $MLFLOW_TRACKING_USERNAME"
          echo "PWD? : ${MLFLOW_TRACKING_PASSWORD:+YES}"
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run training script
        run: |
          python modeling.py

      - name: Get latest MLflow run_id
        id: get_run
        run: |
          python <<'PY'
          import mlflow, os
          client = mlflow.tracking.MlflowClient()
          exp = client.get_experiment_by_name("students-experiment")
          if exp is None:
              raise Exception("Experiment 'students-experiment' not found!")
          runs = client.search_runs(exp.experiment_id, order_by=["start_time DESC"], max_results=1)
          run_id = runs[0].info.run_id
          print("Found RUN_ID:", run_id)
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"run_id={run_id}\n")
          PY

      - name: Download model artifacts
        run: |
          mlflow artifacts download \
            --run-id ${{ steps.get_run.outputs.run_id }} \
            --artifact-path model \
            -d ./model_dir

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: rf_model
          path: ./model_dir

      - name: Build Docker image
        run: |
          mlflow models build-docker \
            --model-uri ./model_dir \
            --name smithdilah/student-performance-model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag smithdilah/student-performance-model smithdilah/student-performance-model:latest
          docker push smithdilah/student-performance-model:latest
