name: CI/CD MLflow Students

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/smithdilah/students_dagshub.mlflow
  MLFLOW_TRACKING_USERNAME: smithdilah
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Train Model
        run: |
          cd MLProject
          python modeling.py

      - name: Get latest run_id
        id: get_run
        run: |
          echo "import mlflow" > get_run.py
          echo "mlflow.set_tracking_uri(\"$MLFLOW_TRACKING_URI\")" >> get_run.py
          echo "mlflow.set_tracking_uri(\"$MLFLOW_TRACKING_URI\")" >> get_run.py
          echo "from mlflow.tracking import MlflowClient" >> get_run.py
          echo "client = MlflowClient()" >> get_run.py
          echo "runs = client.search_runs(experiment_ids=['0'], order_by=['start_time DESC'], max_results=1)" >> get_run.py
          echo "run_id = runs[0].info.run_id" >> get_run.py
          echo "print(f'RUN_ID={run_id}')" >> get_run.py
          echo "with open(\"$GITHUB_ENV\", \"a\") as f: f.write(f'RUN_ID={run_id}\n')" >> get_run.py
          python get_run.py

      - name: Download Artifacts
        run: |
          mkdir -p model_artifact
          mlflow artifacts download -r $RUN_ID -a model -d model_artifact --tracking-uri $MLFLOW_TRACKING_URI --username $MLFLOW_TRACKING_USERNAME --password $MLFLOW_TRACKING_PASSWORD

      - name: Create MLmodel file
        run: |
          echo "" > model_artifact/MLmodel
          echo "flavors:" >> model_artifact/MLmodel
          echo "  python_function:" >> model_artifact/MLmodel
          echo "    loader_module: mlflow.sklearn" >> model_artifact/MLmodel
          echo "    data: model.pkl" >> model_artifact/MLmodel
          echo "    env: conda.yaml" >> model_artifact/MLmodel

      - name: Build Docker image
        run: |
          mlflow models build-docker --model-uri ./model_artifact --name students-performance-model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag students-performance-model nurfdlh/students-performance-model:latest

      - name: Push Docker Image
        run: |
          docker push nurfdlh/students-performance-model:latest
